version: '3.7'

services:
  mongodb:
    image: bitnami/mongodb:4.4.6
    ports:
      - 27017:27017
    environment:
      MONGODB_ROOT_PASSWORD: webinar
      MONGODB_USERNAME: webinar
      MONGODB_PASSWORD: webinar
      MONGODB_DATABASE: webinar
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_NAME: rs0
      MONGODB_REPLICA_SET_KEY: secret

  ticketeer:
    build: .
    init: true
    ports:
      - 80:80
    environment:
      PORT: 80
